# -*- coding: utf-8 -*-
"""deployment_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEcaLmjpq0s6as9dLp27Pu4muYWgfMBG
"""

import streamlit as st
import pandas as pd
import pickle
import gdown
import os

# Load model & fitur
@st.cache_data
def load_model_and_features():
    with open("best_model.pkl", "rb") as f:
        model = pickle.load(f)
    with open("model_features.pkl", "rb") as f:
        feature_order = pickle.load(f)
    return model, feature_order

def download_model_files():
    model_url = "https://drive.google.com/uc?id=1ZkLIEAwdfOVB3bVMOTMnlZyRi_V5u2K7"
    feat_url = "https://drive.google.com/uc?id=1PsJGNFDGzhdSjnjiM3FCTSQEe2TNkdh8"

    if not os.path.exists("best_model.pkl"):
        gdown.download(model_url, "best_model.pkl", quiet=False)

    if not os.path.exists("model_features.pkl"):
        gdown.download(feat_url, "model_features.pkl", quiet=False)

download_model_files()

model, feature_order = load_model_and_features()

# Sidebar
st.sidebar.title("Hotel Booking Status Prediction")
st.sidebar.write("Masukkan informasi pemesanan di bawah ini:")

# Input user
input_data = {
    "no_of_adults": st.sidebar.slider("Jumlah Dewasa", 1, 4, 2),
    "no_of_children": st.sidebar.slider("Jumlah Anak-anak", 0, 3, 0),
    "no_of_weekend_nights": st.sidebar.slider("Malam Weekend", 0, 5, 1),
    "no_of_week_nights": st.sidebar.slider("Malam Weekday", 0, 10, 2),
    "lead_time": st.sidebar.slider("Lead Time (hari)", 0, 500, 30),
    "arrival_year": st.sidebar.selectbox("Tahun Kedatangan", [2017, 2018]),
    "arrival_month": st.sidebar.slider("Bulan Kedatangan", 1, 12, 5),
    "arrival_date": st.sidebar.slider("Tanggal Kedatangan", 1, 31, 15),
    "repeated_guest": st.sidebar.selectbox("Tamu Berulang?", [0, 1]),
    "no_of_previous_cancellations": st.sidebar.slider("Cancel Sebelumnya", 0, 5, 0),
    "no_of_previous_bookings_not_canceled": st.sidebar.slider("Pemesanan Sukses Sebelumnya", 0, 10, 0),
    "avg_price_per_room": st.sidebar.slider("Harga Rata-Rata / Kamar", 0.0, 300.0, 100.0),
    "no_of_special_requests": st.sidebar.slider("Jumlah Permintaan Khusus", 0, 5, 0),
    "required_car_parking_space": st.sidebar.selectbox("Minta Parkir?", [0, 1]),
}

# Placeholder kolom one-hot
for col in feature_order:
    if col not in input_data:
        input_data[col] = 0

# Susun input sesuai urutan fitur
input_df = pd.DataFrame([input_data])
input_df = input_df[feature_order]

# Prediksi
prediction = model.predict(input_df)[0]
probability = model.predict_proba(input_df)[0][prediction]

# Output
st.title("🔍 Prediksi Status Booking Hotel")
if prediction == 1:
    st.success(f"✅ Prediksi: Not Canceled ({probability:.2%} confidence)")
else:
    st.error(f"❌ Prediksi: Canceled ({probability:.2%} confidence)")